name: Hello Pull Requests
on:
  pull_request:
    types: [opened]
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - shell: bash
        run: |
          echo ${{ runner.os }} > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: MP-TEST-PUBLIC-LOG-FILE
          path: ./.github/output.log
